theme: jekyll-theme-minimal
title: Richard Walker
logo: walker87.github.io/images/R&W-64.jpg
description: When Richard isn’t authoring technical documents, he enjoys keeping fit, growing his own vegetables and gardening, travelling, eating sushi and reading Stephen King novels. 
