theme: jekyll-theme-minimal
avatar: "/images/R&W-64.jpg"
title-img: "/images/R&W-64.jpg"
title-img: walker87.github.io/images/r&w-64.jpg
title-img: "walker87.github.io/images/r&w-64.jpg"
navbar-img: "/images/R&W-64.jpg"
navbar-img: "walker87.github.io/images/R&W-64.jpg"
description: Technical Author
