theme: jekyll-theme-minimal
title: Richard Walker
description: Skilled in
description: Markup Languages HTML, XML, CSS, JSON, Markdown
description: Code Repositories GitHub, Team Foundation Server
description: Tools/Applications MadCap Flare, Dita Open Toolkit, Adobe Technical Communications Suite, Swagger
description: Editors Oxygen, Notepad ++ 
